Following are the ways to generate numpy arrays 

In [2]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
my_matrix = [[9,8,7],[6,5,4],[3,2,1]]

In [56]:
np.array(my_matrix)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [10]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [12]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

linspace returns z evenly spaced data points specified in (start - x, end - y ,number of points - z)

In [19]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

np.eye to create identity matrix with n * n 

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Numpy methods to create arrays of random number

In [20]:
np.random.rand(5)

array([0.79737586, 0.15624982, 0.2284627 , 0.81147847, 0.83404833])

In [21]:
np.random.rand(2,2)

array([[0.06683409, 0.4143548 ],
       [0.46191806, 0.9804366 ]])

To generate n randome integers within a range from x to y, we use randint(x,y,n)

In [29]:
arr = np.random.randint(5, 55, 25)

In [30]:
arr.reshape(5,5)

array([[27, 48, 17, 31, 19],
       [26, 34, 33, 27, 40],
       [40, 42, 40, 53, 26],
       [26, 40, 23, 31, 50],
       [42, 16, 10, 29, 45]])

In [31]:
arr.min()

10

In [32]:
arr.max()

53

In [33]:
arr.argmin()

22

In [34]:
arr.argmax()

13

Numpy indexing and selection: numpy arrays are different from python arrays in the way they broadcast values. Also, Slicing doesnot create a copy of array. It works on the original array. If you broadcast and change value on slice, the original array would be change, instead use arr.copy()

In [47]:
arr = np.arange(5, 20)
slice_arr = arr[5:10]

In [49]:
slice_arr[:] = -1111

In [50]:
arr

array([    5,     6,     7,     8,     9, -1111, -1111, -1111, -1111,
       -1111,    15,    16,    17,    18,    19])

In [51]:
slice_arr

array([-1111, -1111, -1111, -1111, -1111])

In [52]:
copy = arr.copy()

In [55]:
copy[5:10] = 222 
copy

array([  5,   6,   7,   8,   9, 222, 222, 222, 222, 222,  15,  16,  17,
        18,  19])

In [64]:
matrix = np.random.rand(5,5)
matrix

array([[0.68643361, 0.28509028, 0.19036785, 0.2537644 , 0.63096488],
       [0.65815485, 0.90460043, 0.8402683 , 0.10272642, 0.89558282],
       [0.67286532, 0.25097225, 0.92101115, 0.44310285, 0.601356  ],
       [0.84704764, 0.97403738, 0.38635413, 0.45723978, 0.74964341],
       [0.69932189, 0.58385849, 0.86860186, 0.11865384, 0.49212103]])

Beautiful!! get portion of matrix

In [62]:
matrix[2:,:3]

array([[0.7640704 , 0.26866419, 0.47393049],
       [0.39046375, 0.43504476, 0.40521038],
       [0.32956956, 0.01099881, 0.1044209 ]])

# Amazing stuff

In [7]:
arr_b = np.arange(5,30, 4)
arr_b

array([ 5,  9, 13, 17, 21, 25, 29])

If we perform comparison like following, it compare each element of array and return boolean values as array. We can pass the output boolean array in original array to select the values conditionally, returns elements of original array(arr_b) where bool_arr is true.

In [10]:
bool_arr = arr_b > 20

In [11]:
arr_b[bool_arr]

array([21, 25, 29])

In [14]:
arr_b[arr_b > 20]

array([21, 25, 29])