In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
my_matrix = [[9,8,7],[6,5,4],[3,2,1]]

In [11]:
np.array(my_matrix)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [10]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [12]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

linspace returns z evenly spaced data points specified in (start - x, end - y ,number of points - z)

In [19]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])