# NumPy Operations

### Array with array  +, -, *, /
### Array with scalars +, -, *, /
### Universal Array Functions 

In [1]:
import numpy as np

In [2]:
arr = np.arange(5, 20)

In [3]:
arr + arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [4]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
1 /arr

array([0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [6]:
arr ** 2

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225, 256, 289,
       324, 361])

In [7]:
np.sqrt(arr)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])